### ISSUE TITLE
storage.get takes forever and never downloads when using BlobId.of(bckt, name)

### ISSUE THREAD

**Issue by RichardLindhout** [googleapis/java-storage#1308]
I have the following code code in my Java Spring Boot application
```java
 // download image
        var imagePath = Paths.get(name);
        logger.info("downloading image {} {}", storageObject.getBucket(), storageObject.getName());
        var blob = storage.get(BlobId.of(storageObject.getBucket(), storageObject.getName()));
        logger.info("got blob");

        if (blob == null || !blob.exists()) {
            logger.info("blob does not exist any more, is probably deleted {}", storageObject.getName());
            return true;
        }
        logger.info("downloadTo {}", imagePath);
        blob.downloadTo(imagePath);
        logger.info("downloaded! {} {}", storageObject.getBucket(), storageObject.getName());
```
Logs
```
n.o.m.s.GoogleCloudStorageSubscriber     : handle event with extension jpg product/219168/0001.jpg
n.o.m.s.GoogleCloudStorageSubscriber     : downloading image omoda-media-pre-processing-2 product/219168/0001.jpg
```

It never goes further than the storage.get line and I'm waiting like half an hour or so. it never logs `got blob`.
I don't know what it could be. Is this some kind of silent error handling in the library?

Version
```xml
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-storage</artifactId>
    <version>2.4.5</version>
</dependency>
<dependency>
    <groupId>com.google.apis</groupId>
    <artifactId>google-api-services-storage</artifactId>
    <version>v1-rev20220210-1.32.1</version>
</dependency>
```

**Comment by RichardLindhout** [comment]
It's fixed with removing BlobId

```
var blob = storage.get(storageObject.getBucket(), storageObject.getName())
```

It strange that the BlobId thing does not work since I thought it was in de documentation on some places.

**Comment by sydney-munro** [comment]
There is no silent error handling that I have been able to find in that code path. Also the method you mention working is just a wrapper around the method you say does not work.

See: https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java#L269-L272

I will try to replicate this problem but as general advise it is always advisable to keep the most up to date version of our client.

**Comment by sydney-munro** [comment]
Since there was a few days in between the swap to `storage.get(storageObject.getBucket(), storageObject.getName())` can you validate that the original code path `storage.get(BlobId.of(storageObject.getBucket(), storageObject.getName()));` is still hanging?

**Comment by RichardLindhout** [comment]
Hmm it also could be that I set the repo on public instead of private!

**Comment by sydney-munro** [comment]
are you still experiencing this issue on `storage.get(BlobId.of(storageObject.getBucket(), storageObject.getName()));`?

**Comment by RichardLindhout** [comment]
Not anymore, but it seems like if the bucket is not public it does not work.
